version: '3.8'

services:
  postgres:
    container_name: machado-finance-api_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: machado
      POSTGRES_PASSWORD: machado
      POSTGRES_DB: machadoFinanceDB
    volumes:
      - postgres_data:/var/lib/postgresql/data      
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: machado-finance-api_redis
    ports:
      - "6379:6379"
    restart: always
volumes:
  postgres_data:
