"""allocation contribuitions flow

Revision ID: 19e2a3876803
Revises: 3de20d5a4844
Create Date: 2026-06-22 18:03:50.519443

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "19e2a3876803"
down_revision: Union[str, Sequence[str], None] = "3de20d5a4844"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_contributions",
        sa.Column("finance_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("contributor_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=False),
        sa.Column("reference_month", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finance_id"],
            ["finances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "allocation_contribution_finance_id_idx",
        "allocation_contributions",
        ["finance_id"],
    )
    op.create_index(
        "allocation_contribution_account_id_idx",
        "allocation_contributions",
        ["account_id"],
    )
    op.create_index(
        "allocation_contribution_allocation_id_idx",
        "allocation_contributions",
        ["allocation_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("allocation_contribution_account_id_idx"),
        table_name="allocation_contributions",
    )
    op.drop_index(
        op.f("allocation_contribution_allocation_id_idx"),
        table_name="allocation_contributions",
    )
    op.drop_index(
        op.f("allocation_contribution_finance_id_idx"),
        table_name="allocation_contributions",
    )
    op.drop_table("allocation_contributions")
    # ### end Alembic commands ###
