"""fix allocation_contribution_month foreign key

Revision ID: 20f12bd470f4
Revises: a24f4be45b95
Create Date: 2026-07-02 10:09:04.060405

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "20f12bd470f4"
down_revision: Union[str, Sequence[str], None] = "a24f4be45b95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("account_finance_id_idx"), table_name="accounts")
    op.drop_index(op.f("account_name_code"), table_name="accounts")
    op.drop_index(
        op.f("allocation_contribution_month_allocation_contribution_id_idx"),
        table_name="allocation_contribution_months",
    )
    op.drop_constraint(
        op.f("allocation_contribution_months_allocation_contribution_id_fkey"),
        "allocation_contribution_months",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "allocation_contribution_months",
        "allocation_contributions",
        ["allocation_contribution_id"],
        ["id"],
    )
    op.drop_index(
        op.f("allocation_contribution_account_id_idx"),
        table_name="allocation_contributions",
    )
    op.drop_index(
        op.f("allocation_contribution_allocation_id_idx"),
        table_name="allocation_contributions",
    )
    op.drop_index(
        op.f("allocation_contribution_finance_id_idx"),
        table_name="allocation_contributions",
    )
    op.drop_index(op.f("allocation_finance_id_idx"), table_name="allocations")
    op.drop_index(op.f("allocation_name_code"), table_name="allocations")
    op.drop_index(op.f("category_finance_id_idx"), table_name="categories")
    op.drop_index(op.f("expenses_account_id_idx"), table_name="expenses")
    op.drop_index(op.f("expenses_allocation_id_idx"), table_name="expenses")
    op.drop_index(op.f("expenses_category_id_idx"), table_name="expenses")
    op.drop_index(op.f("expenses_finance_id_idx"), table_name="expenses")
    op.drop_index(op.f("finance_user_id_idx"), table_name="finances")
    op.drop_index(op.f("incomes_month_income_id_idx"), table_name="income_months")
    op.drop_index(op.f("income_account_id_idx"), table_name="incomes")
    op.drop_index(op.f("income_finance_id_idx"), table_name="incomes")
    op.drop_index(op.f("income_source_code"), table_name="incomes")
    op.drop_index(op.f("transfers_finance_id_idx"), table_name="transfers")
    op.drop_index(op.f("transfers_from_account_id_idx"), table_name="transfers")
    op.drop_index(op.f("transfers_to_account_id_idx"), table_name="transfers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("transfers_to_account_id_idx"),
        "transfers",
        ["to_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("transfers_from_account_id_idx"),
        "transfers",
        ["from_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("transfers_finance_id_idx"), "transfers", ["finance_id"], unique=False
    )
    op.create_index(
        op.f("income_source_code"), "incomes", ["source_code"], unique=False
    )
    op.create_index(
        op.f("income_finance_id_idx"), "incomes", ["finance_id"], unique=False
    )
    op.create_index(
        op.f("income_account_id_idx"), "incomes", ["account_id"], unique=False
    )
    op.create_index(
        op.f("incomes_month_income_id_idx"),
        "income_months",
        ["income_id"],
        unique=False,
    )
    op.create_index(op.f("finance_user_id_idx"), "finances", ["user_id"], unique=False)
    op.create_index(
        op.f("expenses_finance_id_idx"), "expenses", ["finance_id"], unique=False
    )
    op.create_index(
        op.f("expenses_category_id_idx"), "expenses", ["category_id"], unique=False
    )
    op.create_index(
        op.f("expenses_allocation_id_idx"), "expenses", ["allocation_id"], unique=False
    )
    op.create_index(
        op.f("expenses_account_id_idx"), "expenses", ["account_id"], unique=False
    )
    op.create_index(
        op.f("category_finance_id_idx"), "categories", ["finance_id"], unique=False
    )
    op.create_index(
        op.f("allocation_name_code"), "allocations", ["name_code"], unique=False
    )
    op.create_index(
        op.f("allocation_finance_id_idx"), "allocations", ["finance_id"], unique=False
    )
    op.create_index(
        op.f("allocation_contribution_finance_id_idx"),
        "allocation_contributions",
        ["finance_id"],
        unique=False,
    )
    op.create_index(
        op.f("allocation_contribution_allocation_id_idx"),
        "allocation_contributions",
        ["allocation_id"],
        unique=False,
    )
    op.create_index(
        op.f("allocation_contribution_account_id_idx"),
        "allocation_contributions",
        ["account_id"],
        unique=False,
    )
    op.drop_constraint(None, "allocation_contribution_months", type_="foreignkey")
    op.create_foreign_key(
        op.f("allocation_contribution_months_allocation_contribution_id_fkey"),
        "allocation_contribution_months",
        "finances",
        ["allocation_contribution_id"],
        ["id"],
    )
    op.create_index(
        op.f("allocation_contribution_month_allocation_contribution_id_idx"),
        "allocation_contribution_months",
        ["allocation_contribution_id"],
        unique=False,
    )
    op.create_index(op.f("account_name_code"), "accounts", ["name_code"], unique=False)
    op.create_index(
        op.f("account_finance_id_idx"), "accounts", ["finance_id"], unique=False
    )
    # ### end Alembic commands ###
