"""income flow

Revision ID: 3de20d5a4844
Revises: ace0c0cd043c
Create Date: 2026-06-22 16:06:27.174997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3de20d5a4844"
down_revision: Union[str, Sequence[str], None] = "ace0c0cd043c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "incomes",
        sa.Column("finance_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("source_code", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference_month", sa.Integer(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["finance_id"],
            ["finances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index("income_finance_id_idx", "incomes", ["finance_id"])
    op.create_index("income_account_id_idx", "incomes", ["account_id"])
    op.create_index("income_source_code", "incomes", ["source_code"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("income_account_id_idx"), table_name="incomes")
    op.drop_index(op.f("income_finance_id_idx"), table_name="incomes")
    op.drop_index(op.f("income_source_code"), table_name="incomes")
    op.drop_table("incomes")
    # ### end Alembic commands ###
