"""transaction flow

Revision ID: 67ded50d6992
Revises: 86e5c676f9d7
Create Date: 2026-06-23 08:37:32.317990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '67ded50d6992'
down_revision: Union[str, Sequence[str], None] = '86e5c676f9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
                            DO $$ BEGIN
                                CREATE TYPE transactiontypeenum AS ENUM ('INCOME', 'EXPENSE', 'TRANSFER');
                            EXCEPTION
                                WHEN duplicate_object THEN null;
                            END $$;
                        """)
    op.execute("""
                                DO $$ BEGIN
                                    CREATE TYPE transactionstatusenum AS ENUM ('PAID', 'PENDING', 'CANCELLED');
                                EXCEPTION
                                    WHEN duplicate_object THEN null;
                                END $$;
                            """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('finance_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('allocation_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('type', postgresql.ENUM('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontypeenum', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PAID', 'PENDING', 'CANCELLED', name='transactionstatusenum', create_type=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['allocation_id'], ['allocations.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['finance_id'], ['finances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        "transactions_finance_id_idx",
        "transactions",
        ["finance_id"],
    )
    op.create_index(
        "transactions_account_id_idx",
        "transactions",
        ["account_id"],
    )
    op.create_index(
        "transactions_allocation_id_idx",
        "transactions",
        ["allocation_id"],
    )

    op.create_index(
        "transactions_category_id_idx",
        "transactions",
        ["category_id"],
    )

    op.create_index(
        "idx_transactions_date",
        "transactions",
        ["transaction_date"],
    )

    op.create_index(
        "idx_transactions_status",
        "transactions",
        ["status"],
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("transactions_allocation_id_idx"), table_name='transactions')
    op.drop_index(op.f("transactions_account_id_idx"), table_name='transactions')
    op.drop_index(op.f("transactions_finance_id_idx"), table_name='transactions')
    op.drop_index(op.f("transactions_category_id_idx"), table_name='transactions')
    op.drop_index(op.f("idx_transactions_date"), table_name='transactions')
    op.drop_index(op.f("idx_transactions_status"), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
