"""expense months

Revision ID: 74e1cc2cb09b
Revises: 5b492291b320
Create Date: 2026-07-01 19:32:11.044159

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "74e1cc2cb09b"
down_revision: Union[str, Sequence[str], None] = "5b492291b320"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
                                            DO $$ BEGIN
                                                CREATE TYPE monthstatusenum AS ENUM ('PAID', 'PENDING', 'CANCELLED');
                                            EXCEPTION
                                                WHEN duplicate_object THEN null;
                                            END $$;
                                        """)
    op.create_table(
        "expense_months",
        sa.Column("expense_id", sa.Uuid(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=False),
        sa.Column("reference_month", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PAID",
                "PENDING",
                "CANCELLED",
                name="monthstatusenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.drop_column("expenses", "status")
    op.drop_column("expenses", "amount")
    op.drop_column("expenses", "paid_at")
    op.execute("DROP TYPE IF EXISTS expensestatusenum")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
                                        DO $$ BEGIN
                                            CREATE TYPE expensestatusenum AS ENUM ('PAID', 'PENDING', 'CANCELLED');
                                        EXCEPTION
                                            WHEN duplicate_object THEN null;
                                        END $$;
                                    """)

    op.add_column(
        "expenses",
        sa.Column(
            "paid_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "expenses",
        sa.Column(
            "amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "expenses",
        sa.Column(
            "status",
            postgresql.ENUM("PAID", "PENDING", "CANCELLED", name="expensestatusenum"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("expense_months")
    op.execute("DROP TYPE IF EXISTS monthstatusenum")
    # ### end Alembic commands ###
