"""expense flow tables

Revision ID: 7e9111cfa572
Revises: 40c527247885
Create Date: 2026-07-05 16:06:29.858254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7e9111cfa572"
down_revision: Union[str, Sequence[str], None] = "40c527247885"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expenses",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("payee", sa.String(), nullable=False),
        sa.Column("payee_code", sa.String(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["expenses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index("expenses_category_id_idx", "expenses", ["category_id"])
    op.create_index("expenses_allocation_id_idx", "expenses", ["allocation_id"])

    op.execute("""
                                                DO $$ BEGIN
                                                    CREATE TYPE monthstatusenum AS ENUM ('PAID', 'PENDING', 'CANCELLED');
                                                EXCEPTION
                                                    WHEN duplicate_object THEN null;
                                                END $$;
                                            """)

    op.create_table(
        "expense_months",
        sa.Column("expense_id", sa.Uuid(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=False),
        sa.Column("reference_month", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PAID",
                "PENDING",
                "CANCELLED",
                name="monthstatusenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("expenses_month_expense_id_idx", "expense_months", ["expense_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("expenses_month_expense_id_idx"), table_name="expense_months")
    op.drop_table("expense_months")
    op.execute("DROP TYPE IF EXISTS monthstatusenum")
    op.drop_index(op.f("expenses_allocation_id_idx"), table_name="expenses")
    op.drop_index(op.f("expenses_category_id_idx"), table_name="expenses")
    op.drop_table("expenses")
    # ### end Alembic commands ###
