"""category flow

Revision ID: 86e5c676f9d7
Revises: 19e2a3876803
Create Date: 2026-06-22 19:09:04.718712

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "86e5c676f9d7"
down_revision: Union[str, Sequence[str], None] = "19e2a3876803"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
                            DO $$ BEGIN
                                CREATE TYPE categorytypeenum AS ENUM ('FOOD', 'OTHER', 'UTILITY', 'HEALTH', 'PERSONAL', 'TRANSPORT', 'ENTERTAINMENT');
                            EXCEPTION
                                WHEN duplicate_object THEN null;
                            END $$;
                        """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("finance_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_code", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "FOOD",
                "OTHER",
                "UTILITY",
                "HEALTH",
                "PERSONAL",
                "TRANSPORT",
                "ENTERTAINMENT",
                name="categorytypeenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["finance_id"],
            ["finances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_code"),
    )
    op.create_index("category_finance_id_idx", "categories", ["finance_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("category_finance_id_idx"), table_name="categories")
    op.drop_table("categories")
    op.execute("DROP TYPE IF EXISTS categorytypeenum")
    # ### end Alembic commands ###
