"""allocation contribution flow tables

Revision ID: 940ccbaca2e7
Revises: 986be51511e6
Create Date: 2026-07-05 15:55:26.029222

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "940ccbaca2e7"
down_revision: Union[str, Sequence[str], None] = "986be51511e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_contributions",
        sa.Column("allocation_id", sa.Uuid(), nullable=False),
        sa.Column("contributor_name", sa.String(), nullable=False),
        sa.Column("contributor_name_code", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["allocation_id"],
            ["allocations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "allocation_contribution_allocation_id_idx",
        "allocation_contributions",
        ["allocation_id"],
    )

    op.create_table(
        "allocation_contribution_months",
        sa.Column("allocation_contribution_id", sa.Uuid(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=False),
        sa.Column("reference_month", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["allocation_contribution_id"],
            ["allocation_contributions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "allocation_contribution_month_allocation_contribution_id_idx",
        "allocation_contribution_months",
        ["allocation_contribution_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("allocation_contribution_month_allocation_contribution_id_idx"),
        table_name="allocation_contribution_months",
    )
    op.drop_table("allocation_contribution_months")
    op.drop_index(
        op.f("allocation_contribution_allocation_id_idx"),
        table_name="allocation_contributions",
    )
    op.drop_table("allocation_contributions")
    # ### end Alembic commands ###
