"""account flow

Revision ID: 99853d86cfdc
Revises: 2eaf2a39f864
Create Date: 2026-06-20 18:33:38.496900

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "99853d86cfdc"
down_revision: Union[str, Sequence[str], None] = "2eaf2a39f864"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
                        DO $$ BEGIN
                            CREATE TYPE accounttypeenum AS ENUM ('PIX', 'BANK', 'CASH', 'OTHER', 'INVESTMENT', 'CREDIT_CARD', 'ACCOUNT_DEBIT');
                        EXCEPTION
                            WHEN duplicate_object THEN null;
                        END $$;
                    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("finance_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_code", sa.String(), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "PIX",
                "BANK",
                "CASH",
                "OTHER",
                "INVESTMENT",
                "CREDIT_CARD",
                "ACCOUNT_DEBIT",
                name="accounttypeenum",
                create_type=False
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("initial_balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("current_balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["finance_id"],
            ["finances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_code"),
    )
    op.create_index("account_finance_id_idx", "accounts", ["finance_id"])
    op.create_index("account_name_code", "accounts", ["name_code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("accounts")
    op.execute("DROP TYPE IF EXISTS accounttypeenum")
    # ### end Alembic commands ###
