"""users

Revision ID: 527b69285dd7
Revises:
Create Date: 2026-05-26 19:02:18.081676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "527b69285dd7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
                      DO $$ BEGIN
                          CREATE TYPE statusenum AS ENUM ('ACTIVE','INACTIVE','INCOMPLETE');
                      EXCEPTION
                          WHEN duplicate_object THEN null;
                      END $$;
                  """)
    op.execute("""
                      DO $$ BEGIN
                          CREATE TYPE roleenum AS ENUM ('USER','ADMIN');
                      EXCEPTION
                          WHEN duplicate_object THEN null;
                      END $$;
                  """)
    op.create_table(
        "users",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("ACTIVE", "INACTIVE", name="statusenum", create_type=False),
            nullable=False,
        ),
        sa.Column(
            "role",
            postgresql.ENUM("USER", "ADMIN", name="roleenum", create_type=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.execute("DROP TYPE IF EXISTS statusenum")
    op.execute("DROP TYPE IF EXISTS roleenum")
    # ### end Alembic commands ###
