"""allocation contribution month

Revision ID: a24f4be45b95
Revises: d31fe2b20921
Create Date: 2026-07-02 09:03:07.843113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a24f4be45b95"
down_revision: Union[str, Sequence[str], None] = "d31fe2b20921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocation_contribution_months",
        sa.Column("allocation_contribution_id", sa.Uuid(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=False),
        sa.Column("reference_month", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["allocation_contribution_id"],
            ["finances.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "allocation_contribution_month_allocation_contribution_id_idx",
        "allocation_contribution_months",
        ["allocation_contribution_id"],
    )

    op.drop_column("allocation_contributions", "amount")
    op.drop_column("allocation_contributions", "reference_month")
    op.drop_column("allocation_contributions", "reference_year")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "allocation_contributions",
        sa.Column("reference_year", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "allocation_contributions",
        sa.Column("reference_month", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "allocation_contributions",
        sa.Column(
            "amount",
            sa.NUMERIC(precision=12, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("allocation_contribution_months")
    # ### end Alembic commands ###
