"""allocation flow

Revision ID: ace0c0cd043c
Revises: 99853d86cfdc
Create Date: 2026-06-22 10:37:52.579605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ace0c0cd043c'
down_revision: Union[str, Sequence[str], None] = '99853d86cfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
                            DO $$ BEGIN
                                CREATE TYPE allocationtypeenum AS ENUM ('HOUSE', 'FAMILY', 'PERSONAL', 'OTHER');
                            EXCEPTION
                                WHEN duplicate_object THEN null;
                            END $$;
                        """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('finance_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column(
        'type',
        postgresql.ENUM('HOUSE', 'FAMILY', 'PERSONAL', 'OTHER', name='allocationtypeenum', create_type=False),
        nullable=False
    ),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finance_id'], ['finances.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name_code')
    )
    op.create_index("allocation_finance_id_idx", "allocations", ["finance_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.execute("DROP TYPE IF EXISTS allocationtypeenum")
    # ### end Alembic commands ###
