"""income months

Revision ID: d31fe2b20921
Revises: 74e1cc2cb09b
Create Date: 2026-07-01 22:16:47.710557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd31fe2b20921'
down_revision: Union[str, Sequence[str], None] = '74e1cc2cb09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "income_months",
        sa.Column("income_id", sa.Uuid(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=False),
        sa.Column("reference_month", sa.Integer(), nullable=False),
        sa.Column("received_at", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["income_id"],
            ["incomes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("incomes_month_income_id_idx", "income_months", ["income_id"])


    op.drop_column('incomes', 'reference_year')
    op.drop_column('incomes', 'received_at')
    op.drop_column('incomes', 'reference_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('reference_month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('incomes', sa.Column('received_at', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('incomes', sa.Column('reference_year', sa.INTEGER(), autoincrement=False, nullable=False))

    op.drop_table('income_months')
    # ### end Alembic commands ###
