"""add parent_id

Revision ID: f88a3d181f24
Revises: a24f4be45b95
Create Date: 2026-07-02 18:43:36.951224

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f88a3d181f24"
down_revision: Union[str, Sequence[str], None] = "a24f4be45b95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expenses", sa.Column("parent_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "expenses_expense_id_fkey", "expenses", "expenses", ["parent_id"], ["id"]
    )
    op.create_index("expense_parent_id_idx", "expenses", ["parent_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index("expense_parent_id_idx", "expenses")
    op.drop_constraint("expenses_expense_id_fkey", "expenses", type_="foreignkey")
    op.drop_column("expenses", "parent_id")

    # ### end Alembic commands ###
