"""Allocation Tabble

Revision ID: fff67768a55c
Revises: eb9a7d7994be
Create Date: 2026-07-05 15:37:17.927098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fff67768a55c"
down_revision: Union[str, Sequence[str], None] = "eb9a7d7994be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allocations",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("name_code", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name_code"),
    )
    op.create_index("allocation_account_id_idx", "allocations", ["account_id"])
    op.create_index("allocation_name_code", "allocations", ["name_code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("allocation_name_code"), table_name="allocations")
    op.drop_index(op.f("allocation_account_id_idx"), table_name="allocations")
    op.drop_table("allocations")
    # ### end Alembic commands ###
